__all__ = ['COUNTRIES']

COUNTRIES = [
    {"id": 1,
     "name": "Australian Dollar",
     "code": "AUD"},
    {"id": 2,
     "name": "British Pound",
     "code": "GBP"},
    {"id": 3,
     "name": "Bulgarian Lev",
     "code": "BGN"},
    {"id": 4,
     "name": "Canadian Dollar",
     "code": "CAD"},
    {"id": 5,
     "name": "Chinese Yuan Renminbi",
     "code": "CNY"},
    {"id": 6,
     "name": "Czech Koruna",
     "code": "CZK"},
    {"id": 7,
     "name": "Danish Krone",
     "code": "DKK"},
    {"id": 8,
     "name": "Emirati Dirham",
     "code": "AED"},
    {"id": 9,
     "name": "Euro",
     "code": "EUR"},
    {"id": 10,
     "name": "Hong Kong Dollar",
     "code": "HKD"},
    {"id": 11,
     "name": "Hungarian Forint",
     "code": "HUF"},
    {"id": 12,
     "name": "Israeli Shekel",
     "code": "ILS"},
    {"id": 13,
     "name": "Japanese Yen",
     "code": "JPY"},
    {"id": 14,
     "name": "Mexican Peso",
     "code": "MXN"},
    {"id": 15,
     "name": "New Zealand Dollar",
     "code": "NZD"},
    {"id": 16,
     "name": "Norwegian Krone",
     "code": "NOK"},
    {"id": 17,
     "name": "Polish Zloty",
     "code": "PLN"},
    {"id": 18,
     "name": "Qatari Rial",
     "code": "QAR"},
    {"id": 19,
     "name": "Romanian New Leu",
     "code": "RON"},
    {"id": 20,
     "name": "Saudi Riyal",
     "code": "SAR"},
    {"id": 21,
     "name": "Singapore Dollar",
     "code": "SGD"},
    {"id": 22,
     "name": "South African Rand",
     "code": "ZAR"},
    {"id": 23,
     "name": "Swedish Krona",
     "code": "SEK"},
    {"id": 24,
     "name": "Swiss Franc",
     "code": "CHF"},
    {"id": 25,
     "name": "Thai Baht",
     "code": "THB"},
    {"id": 26,
     "name": "Turkish Lira",
     "code": "TRY"},
    {"id": 27,
     "name": "United States Dollar",
     "code": "USD"},
]
