version: '2'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        - PYTHONUNBUFFERED=1
        - DEBUG=True
    volumes:
        - .:/code
    expose:
        - "8080"
    ports:
        - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=monpay
      - POSTGRES_PASSWORD=monpayPASS!
      - POSTGRES_DB=monpaydb
    expose:
        - "5432"
    ports:
        - "5432:5432"
